In [1]:
import numpy as np
import math 
from scipy.stats import norm
from scipy.stats import truncnorm
import scipy.stats as stats

In [2]:
import sys
import os

# Add the path to utils.py
sys.path.append(r"c:\Document\Serieux\Travail\python_work\cEBNM_torch\py")

# Import utils.py directly
from utils import *
from numerical_routine import *
from distribution_operation import *
from posterior_computation import *

In [3]:
class cebnm:
    def __init__(self, 
                 betahat,
                 sebetahat,
                 type="norm",
                 X=None,
                 max_class=None,
                 mult=2
                 ):
        self.betahat   = betahat
        self.sebetahat = sebetahat
        self.type      = type       
        self.X         = X
        self.loss      = 0
        
        if self.type== "norm":
            self.scale = autoselect_scales_mix_norm(betahat=betahat,
                                                    sebetahat=sebetahat,
                                                    max_class=max_class,
                                                    mult=mult)  
        elif self.type == "exp":
            self.sale= autoselect_scales_mix_exp   (betahat=betahat,
                                                    sebetahat=sebetahat,
                                                    max_class=max_class,
                                                    mult=mult)  
        self.log_pi    = np.log( 
                                np.full( (self.betahat.shape[0], 
                                   self.scale.shape[0]),
                                 1/self.scale.shape[0])  
                                )      
    def update_posterior(self):
        """Compute and update the posterior mean, mean2, and sd."""
        if(self.type == "norm"):
            posterior_result = posterior_mean_norm(betahat  =self.betahat, 
                                                   sebetahat=  self.sebetahat, 
                                                   log_pi   =  self.log_pi, 
                                                   scale    = self.scale)
        elif(self.type =="exp"):
            posterior_result = posterior_mean_norm(betahat  =self.betahat, 
                                                   sebetahat=  self.sebetahat, 
                                                   log_pi   =  self.log_pi, 
                                                   scale    = self.scale)
        
        
        
        self.post_mean = posterior_result.post_mean
        self.post_mean2 = posterior_result.post_mean2
        self.post_sd = posterior_result.post_sd
            

In [5]:
betahat=  np.array([1,2,3,4,5])
sebetahat=np.array([1,0.4,5,1,1])
model= cebnm ( betahat=betahat,
                 sebetahat=sebetahat)
print(model.betahat)
print(model.scale)
print(model.X)
print(model.sebetahat)
print(model.type)
print(model.loss)
print(model.log_pi)
model.update_posterior()
print(model.post_mean)
print(model.post_mean2)
print(model.post_sd)

[1 2 3 4 5]
[0.         0.03827328 0.07654655 0.15309311 0.30618622 0.61237244
 1.22474487 2.44948974 4.89897949 9.79795897]
None
[1.  0.4 5.  1.  1. ]
norm
0
[[-2.30258509 -2.30258509 -2.30258509 -2.30258509 -2.30258509 -2.30258509
  -2.30258509 -2.30258509 -2.30258509 -2.30258509]
 [-2.30258509 -2.30258509 -2.30258509 -2.30258509 -2.30258509 -2.30258509
  -2.30258509 -2.30258509 -2.30258509 -2.30258509]
 [-2.30258509 -2.30258509 -2.30258509 -2.30258509 -2.30258509 -2.30258509
  -2.30258509 -2.30258509 -2.30258509 -2.30258509]
 [-2.30258509 -2.30258509 -2.30258509 -2.30258509 -2.30258509 -2.30258509
  -2.30258509 -2.30258509 -2.30258509 -2.30258509]
 [-2.30258509 -2.30258509 -2.30258509 -2.30258509 -2.30258509 -2.30258509
  -2.30258509 -2.30258509 -2.30258509 -2.30258509]]
[0.23635376 1.90130825 0.34311694 3.60843288 4.70131272]
[ 0.39779246  3.78405223  3.4020959  14.1843412  23.15589264]
[0.58474726 0.4111924  1.81228217 1.07868129 1.02642651]


In [6]:
print(model.X)

None


In [5]:


# Use the function directly
betahat = np.array([1, 2, 3, 4, 5])
sebetahat = np.array([1, 0.4, 5, 1, 1])

scale = utils.autoselect_scales_mix_norm(betahat, sebetahat)
print(scale)


[0.         0.03827328 0.07654655 0.15309311 0.30618622 0.61237244
 1.22474487 2.44948974 4.89897949 9.79795897]
