In [1]:
import numpy as np

# Parameters
n, p = 50, 40  # Dimensions of the matrix
noise_std = 0.1  # Standard deviation of the homoscedastic noise

# Generate two random vectors
u = np.random.rand(n)  # Vector of length n
v = np.random.rand(p)  # Vector of length p

# Create a rank-1 matrix as the outer product of u and v
rank_1_matrix = np.outer(u, v)

# Add homoscedastic Gaussian noise (constant variance across the matrix)
noise = np.random.normal(0, noise_std, size=(n, p))
noisy_matrix = rank_1_matrix + noise

# Print the original and noisy matrix
print("Rank-1 Matrix (Outer Product):")
print(rank_1_matrix)
print("\nNoisy Matrix (with Homoscedastic Noise):")
print(noisy_matrix)


Rank-1 Matrix (Outer Product):
[[0.11297917 0.31397253 0.37514486 ... 0.56209635 0.0454579  0.12723723]
 [0.09458225 0.26284693 0.31405829 ... 0.47056761 0.03805578 0.10651861]
 [0.13745647 0.38199568 0.45642119 ... 0.68387632 0.05530649 0.15480359]
 ...
 [0.04188835 0.11640899 0.13908935 ... 0.2084038  0.01685405 0.04717469]
 [0.01959423 0.05445295 0.06506221 ... 0.09748562 0.00788386 0.02206704]
 [0.02830421 0.07865826 0.09398351 ... 0.14081971 0.01138838 0.03187623]]

Noisy Matrix (with Homoscedastic Noise):
[[ 0.01152129  0.25956499  0.258771   ...  0.47685686  0.0127428
   0.27747843]
 [-0.01263714  0.19913086  0.15476304 ...  0.29297002 -0.09844083
   0.32558421]
 [ 0.10810724  0.35522071  0.32736028 ...  0.66096272 -0.04827398
   0.37224748]
 ...
 [ 0.07556855  0.09614721  0.22795116 ...  0.13027049 -0.12420913
  -0.16537578]
 [ 0.2368145  -0.02072585  0.13295821 ...  0.27379999 -0.03784046
  -0.05843747]
 [-0.05417099  0.11991049  0.20847755 ...  0.21983256 -0.08298591
   0.050

In [2]:
import sys
import os
import matplotlib.pyplot as plt

# Add the path to utils.py
sys.path.append(r"c:\Document\Serieux\Travail\python_work\cEBNM_torch\py")
from cEBMF import *

In [3]:
mycebmf= cEBMF(data    = noisy_matrix,
               prior_L = "exp",
               prior_F = "exp")
K=5
# Perform udv_si transformation
U, s, Vt = np.linalg.svd(noisy_matrix, full_matrices=False)


mycebmf.init_LF()
 

In [4]:
mycebmf.iter()


exp
(50,)
(50,)


c:\Document\Serieux\Travail\python_work\cEBNM_torch\py\numerical_routine.py:237: RuntimeWarning: invalid value encountered in divide
  w = w / w.sum(axis=0, keepdims=True)  # Normalize by sum over k for each j


AxisError: axis 1 is out of bounds for array of dimension 1

In [5]:
mycebmf= cEBMF(data    = noisy_matrix )
K=5
# Perform udv_si transformation
U, s, Vt = np.linalg.svd(noisy_matrix, full_matrices=False)

 
mycebmf.init_LF()
mycebmf.iter()

norm
(50,)
(50,)
norm
(50,)
(50,)
norm
(50,)
(50,)
norm
(50,)
(50,)
norm
(50,)
(50,)


In [ ]:
mycebmf.update_fitted_val()
plt.scatter(mycebmf.Y_fit, noisy_matrix)
 
plt.scatter(mycebmf.Y_fit, rank_1_matrix)
plt.scatter(np.outer(mycebmf.L[:,0],mycebmf.F[:,0] ), rank_1_matrix)